#!/usr/bin/ruby

# Simple script for converting Haml and CoffeeScript to HTML and JavaScript

require 'coffee-script'
require 'haml'
require 'sass'

$file_exts = { 'coffee' => 'js', 'haml' => 'html', 'scss' => 'css' }

def fwrite(name, contents)
  name.scan /(.+)\.(.+)/ do |base, orig_ext|
    new_ext = $file_exts[orig_ext]
    puts "Converted #{name} to #{new_ext}"
    File.write "#{base}.#{new_ext}", contents
  end
end

Dir.glob '**/*' do |file|
  case File.extname(file)[1..-1]
  when 'coffee'
    fwrite file, CoffeeScript.compile(File.read file)
  when 'haml'
    fwrite file, Haml::Engine.new(File.read file).render
  when 'scss'
    fwrite file, Sass.compile(File.read file)
  end
end
